Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mohamedyousry\mypro\sphinxx\SecurityHome\views.py", line 10, in index
    return render(request, 'index.html',{'client':cl})
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\template\defaulttags.py", line 168, in render
    len_values = len(values)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\query.py", line 269, in __len__
    self._fetch_all()
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 1143, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 498, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 262, in get_select
    sql, params = self.compile(col)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 430, in compile
    sql, params = node.as_sql(self, self.connection)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\expressions.py", line 784, in as_sql
    sql = '.'.join(map(compiler.quote_name_unless_alias, identifiers))
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\models\sql\compiler.py", line 421, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "C:\Users\mohamedyousry\Envs\sphinxproject\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"GET / HTTP/1.1" 500 145
